baseURL: /
languageCode: en
DefaultContentLanguage: en
title: Website of Jane Doe
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
markup:
  goldmark:
    renderer:
      unsafe: yes

ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]


